version: '3.7'

volumes:
    logs:
        driver: local
    dbdata:
        driver: local

services:
    nginx:
        container_name: tools-nginx
        image: nginx:alpine
        restart: always
        ports:
            - 80:80
            # - 443:443
        volumes:
            - ./public/:/var/www/public/
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    php-fpm:
        container_name: tools-php-fpm
        build: docker/php
        working_dir: /var/www
        restart: always
        env_file:
            - .env
        networks:
            - app-network
        volumes:
            - .:/var/www
            - logs:/var/www/logs
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

    composer:
        image: composer:latest
        volumes:
            - .:/app
        stdin_open: true
        tty: true
        command: install

    # phpunit:
    #     build: docker/php
    #     restart: "no"
    #     volumes:
    #         - .:/app
    #     working_dir: /app
    #     entrypoint: vendor/bin/phpunit
    #     environment: 
    #         XDEBUG_MODE: coverage

    mariadb:
        container_name: tools-mariadb
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "welcome1"
            MYSQL_DATABASE: love_you_a_latte
            MYSQL_USER: slimuser
            MYSQL_PASSWORD: welcome1
        ports:
            - 3306:3306
        networks:
            - app-network
        volumes:
            - ./data/:/var/lib/mysql

    # memcached:
    #     image: memcached:alpine
    #     container_name: tools-memcached
    #     ports:
    #         - 11211:11211
    #     networks:
    #         - app-network

networks:
  app-network:
    driver: bridge
