version: '3.7'

volumes:
    logs:
        driver: local
    dbdata:
        driver: local

services:
    nginx:
        container_name: nginx
        image: nginx:alpine
        restart: always
        ports:
            - 80:80
            # - 443:443
        volumes:
            - ./public/:/var/www/public/
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    php-fpm:
        container_name: php-fpm
        build: docker/php
        working_dir: /var/www
        restart: always
        env_file:
            - .env
        networks:
            - app-network
        volumes:
            - .:/var/www
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

    composer:
        container_name: php-composer
        image: composer:latest
        volumes:
            - .:/app
        stdin_open: true
        tty: true
        command: install

    mariadb:
        container_name: mariadb
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "welcome1"
            MYSQL_DATABASE: love_you_a_latte
            MYSQL_USER: slimuser
            MYSQL_PASSWORD: welcome1
        ports:
            - 3306:3306
        networks:
            - app-network
        volumes:
            - ./data/:/var/lib/mysql
            - ./docker/mariadb/init/:/docker-entrypoint-initdb.d
    node-red:
        container_name: node-red
        image: nodered/node-red:latest
        environment:
          - TZ=US/Eastern
        ports:
          - "1880:1880"
        volumes:
          - ./docker/node-red:/data
        networks:
          - app-network

networks:
  app-network:
    driver: bridge
